services:
  tile-db:
    image: docker.io/mariadb:latest
#    env_file:
#      - ./config/secret.env
#    container_name: tilearchive-container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - tile-volume:/var/lib/mysql
      - ./glaze_daemon/db-schema.sql:/docker-entrypoint-initdb.d/db-schema.sql
    networks:
      - glazed

  glazer-admin:
    build: ./glazer_admin
#    image: localhost/cacticouncil/ceramnote_frontend:latest
#    container_name: ceramnote-frontend
    ports:
      - "80:80"
    depends_on:
      - tile-db
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data:/data
    networks:
      - glazed

  glaze-daemon:
    build: ./glaze_daemon
#    image: cacticouncil/ceramnote_backend:latest
    container_name: glaze-daemon
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    depends_on:
      - tile-db
      - chroma
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - glazed

  chroma:
    image: docker.io/chromadb/chroma:latest
    ports:
      - "8001:8000"
    volumes:
      - ./data/chroma:/chroma/chroma
    networks:
      - glazed

volumes:
  tile-volume:
  data-volume:

# Added all of this
networks:
  glazed:
    driver: bridge
