services:
  tile-db:
    image: docker.io/mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - tile-volume:/var/lib/mysql
      - ./glaze_daemon/db-schema.sql:/docker-entrypoint-initdb.d/db-schema.sql
    networks:
      - glazed

  glazer-admin:
    build: ./glazer_admin
    ports:
      - "80:80"
    depends_on:
      - tile-db
      - glaze-daemon
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data:/data
    networks:
      - glazed

  glaze-daemon:
    build: ./glaze_daemon
    container_name: glaze-daemon
    ports:
      - "8000:8000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${MYSQL_DATABASE}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      CHROMA_HOST: chroma
      CHROMA_PORT: 8000
      HF_HOME: /data/huggingface
    volumes:
      - ./data:/data
    depends_on:
      - tile-db
      - chroma
    networks:
      - glazed

  chroma:
    image: docker.io/chromadb/chroma:latest
    ports:
      - "8001:8000"
    volumes:
      - ./data/chroma:/data
    networks:
      - glazed

volumes:
  tile-volume:
  data-volume:

networks:
  glazed:
    driver: bridge
